"""add stats flag to study

Revision ID: 1fb6c6b2d1a3
Revises: 3bd6d6fa76f0
Create Date: 2026-06-15 13:25:09.049273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb6c6b2d1a3'
down_revision: Union[str, Sequence[str], None] = '3bd6d6fa76f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('stats', sa.Boolean(), nullable=True, comment='Whether the study is selected for statistics.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'stats')
    # ### end Alembic commands ###
