"""add repository table

Revision ID: 3b7ccd2db9b6
Revises: 22055080ce6c
Create Date: 2026-04-29 15:55:24.676379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '3b7ccd2db9b6'
down_revision: Union[str, Sequence[str], None] = '22055080ce6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='FASTQs'
    )
    op.create_index(op.f('ix_repository_id'), 'repository', ['id'], unique=False)
    op.create_index(op.f('ix_repository_name'), 'repository', ['name'], unique=True)
    # ### end Alembic commands ###
    
    repository_table = table('repository',
        column('id', sa.Integer),
        column('name', sa.String)
    )
    
    # Insert the default repository (id=1)
    op.bulk_insert(
        repository_table,
        [
            {'id': 1, 'name': 'My Lab Repository'},
        ]
    )
    # ### END SEED DATA ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_name'), table_name='repository')
    op.drop_index(op.f('ix_repository_id'), table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###