"""add properties to user

Revision ID: df4c479cdecc
Revises: 1fb6c6b2d1a3
Create Date: 2026-07-28 18:13:47.679425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4c479cdecc'
down_revision: Union[str, Sequence[str], None] = '1fb6c6b2d1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('properties', sa.JSON(), nullable=True))
    op.add_column('sample', sa.Column('sequencing_type', sa.Enum('BULK', 'SINGLE_CELL', 'TEN_X', name='sequencingtype'),
                                      nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('user', 'properties')
    op.drop_column('sample', 'sequencing_type')
